### ISSUE TITLE
PHP CS Fixer not working :(

### ISSUE THREAD

**Issue by devdrops** [devdrops/php-toolbox#9]
Seems that running PHP CS Fixer does not makes any changes to the target files. Why?

Execution:
```
docker run -it -v $(pwd):/foo -w /foo devdrops/php-toolbox php-cs-fixer fix my/awesome/php/file.php

docker run -it -v $(pwd):/foo -w /foo devdrops/php-toolbox php-cs-fixer fix /foo/my/awesome/php/file.php
```

**Comment by atmosmps** [comment]
This is still a problem? I tested the PHP CS Fixer service on a project and it seems to have worked normally. What specifically isn't working?

**Comment by devdrops** [comment]
Fala @atmosmps, tudo certo meu caro?

Até onde me lembro, o problema em questão era ligado à falta de permissão de acesso do php-cs-fixer aos arquivos PHP.

Se puder compartilhar aqui um exemplo de como foi o seu teste, eu agradeço!

**Comment by devdrops** [comment]
Resolvido :tada:
